### PR TITLE
Made more modern

### PR DESCRIPTION
**Pull request by ghanteyyy**
Following changes are made:

- Re-located files directory.
- Re-designed from scratch.
- Added automatic testing script.
- Real-time visualization of changes in pie-chart.
- Removed many widgets to make more user-friendly.

### CODE REVIEW

**Comment by NMrocks** [comment]
Hey, glad to see you're still contributing to this project that I've myself stopped contributing to :)

I'm currently a bit busy with my school exams and won't be able to merge this for the next few days, sorry for the delay

I'll test your PR and merge it ASAP after my exams are over. TY again for the contributions.

**Comment by ghanteyyy** [comment]
I've always wanted to made it more interactive and dynamic but was busy on my own projects so it took long time to to make changes.  I have still some changes to do so there will be another pull request after you merge it. And after that I think the project will be done for forever **(but there will always be some rooms for improvements).** 

### And Goodluck for your exams.

**Comment by NMrocks** [comment]
Hey sorry for the late response but I can't seem to be able to get this to work on Linux, there are multiple things that need to be fixed for this to work on Linux (i fixed some issues, the program starts but the GUI that shows up is just invisible). I use Linux distros as my daily drivers and it'll be a shame if one of my own programs don't work on Linux lol

I will have to test this on Windows to see if it actually works. I don't get much time to code and so I couldn't test it on Windows, but I will and I will update you on this

BTW the name of the PCC logo file seems to be wrong in the code, did you really test the code you wrote before making the PR?

**Comment by NMrocks** [comment]
It works on Windows, so I'll merge this I guess. I might fix the Linux issues later

Regarding the name of the PCC logo file: Windows seems to expose NTFS as case-insensitive to programs accessing the filesystem, which means the code works with the wrong case on Windows but doesn't on Linux, another thing to fix

**Comment by ghanteyyy** [comment]
I didn't understand what you meant by the PCC logo file. **Could you please elaborate it ?** I don't work in Linux so I don't have any idea regarding to it. I have tested it on my Windows 11 and it works like a charm.

**Comment by ghanteyyy** [comment]
I think I have understood what you meant. **Logo is not supported in Linux right ?** Do you have the logo in **png format ?**

**Pull request merged**
